<?php include('UserHeader.php');

$val = !empty($_SESSION["uid_session"])?$_SESSION:" ";

if($val == " ")
{
	echo"<script>window.location.href='Login.php?login=user'</script>";
}
$uid_session = $_SESSION["uid_session"];

$casetype = $_GET['casetype'];

?>

<div class="content">  
	<div class="container">
	<h4 style="float:left;"><i class="fa fa-arrow-left" style="font-size:18px;color:blue"></i><a href="ViewCase.php?casetype=<?php echo $casetype ?>">View Case</a></h4>
	
	</br>
	
		<div class="col-md-12 col-lg-12">
		<h4>About Network Forensics</h4></br>
		
<p>Network Forensics is a sub-branch of Digital Forensics which refers to the investigation and analysis of all traffic going across a network suspected of use in a cyber crime. Usually, investigators would look for data that points towards human communication or manipulation of files through a network. </p>
</br>

<h4>Why Network Forensics?</h4></br>

Criminals attack computer systems for a number of reasons, but primarily for economic gain. Among the most common targets are banking and other personal information stored on PCs and servers that will assist in completing fraudulent financial transactions. 
Network forensics—defined as the investigation of network traffic patterns and data captured in transit between computing devices—can provide insight into the source and extent of an attack. It also can supplement investigations focused on information left behind on computer hard drives following an attack.</br>
What can you find in a thorough network analysis?
•	Full packet data capture
•	Transmission and Application Protocols
•	Log files
•	Traffic patterns
•	Recognize malicious activity
•	Intrusion detection

</br>
Network forensics ensures a faster incident response to an attack. It provides the ability to investigate the attacks by tracing the attack back to the source and discovering the nature of the attacker if it is a person, host or a network. In addition, network forensics provides methods to predict future attacks by correlating attack patterns from previous records of intrusion traffic data. This facilitates the presentation of admissible evidence in a court of law.</br></br>
<b>Terminologies:</b></br></br>

<b>IPv4 Protocol:</b> It is the fourth revision of the Internet Protocol and a widely used protocol in data communication over different kinds of networks.</br></br>
<b>SIP (Session Initiation Protocol):</b> This protocol is used in VoIP technology and is an application layer protocol that is used for initiating, maintaining, and terminating real-time sessions that include voice, video and messaging applications. Meaning, it controls multimedia communication sessions over the Internet.</br></br>
<b>SIP Flow:</b> SIP Flows show a basic SIP call session between two entities.</br></br>
<b>RTP (Real Time Transport Protocol):</b> It is an Internet Protocol that helps programs to manage real-time transmission of multimedia data. Basically, The Real Time Transport Protocol is able to code multimedia data streams such as audio or video, divide them into packets and transmit them over an IP network.</br></br>
<b>Telephony:</b> The technology involving the development, application, and deployment of telecommunication services for the purpose of electronic transmission of voice, fax, or data, between distant parties.
Wireshark provides a wide range of telephony related network statistics which can be accessed via the Telephony menu. These statistics range from specific signaling protocols, to analysis of signaling and media flows. If encoded in a compatible encoding the media flow can even be played.</br></br>
<b>Payload:</b> When data is sent over the Internet, each unit transmitted includes both header information and the actual data being sent. The header identifies the source and destination of the packet, while the actual data is referred to as the payload.
Rtpdump:
•	Rtpplay
Play back RTP sessions recorded by rtpdump

•	Rtpsend
Generate RTP packets from textual description, generated by hand or rtpdump

•	Rtpdump
Parse and print RTP packets, generating output files suitable for rtpplay and rtpsend</br></br>

<b>FTP (File Transfer Protocol):</b> Protocol used for exchanging files between a client and server over a network.</br></br>
<b>Log files:</b> A file that records events that occur over the network, like messaging between different users over a network connection, for example.
</br>
</br>

<b>Learning Outcomes:</b></br>
1.	SIP packet analysis
2.	Log Analysis of FTP server 
3.	Communication between two end-user machines
4.	Use of Wireshark for evidence analysis


		</div>
		
		<div class="col-md-12 col-lg-12 text-center" style="margin-top:3%;">
		<?php
		
		if(isset($_GET['caseid_new']))
		{
			$caseid = $_GET['caseid_new'];
			
			echo '<a href="ViewCase_Yes.php?casetype='.$casetype.'&caseid_new='.$caseid.'" class="btn btn-primary" style="width:10%;">Start</a>';
		}
		else
		{
			$caseid = $_GET['caseid'];
			
			echo '<a href="ViewCase_Yes.php?casetype='.$casetype.'&caseid='.$caseid.'" class="btn btn-primary" style="width:10%;">Start</a>';
		}
				
		?>
			
		</div>
		
		
	</div>		
</div>
</br>
		
<?php include('footer.php') ?>